### ISSUE TITLE
Pulsar function trigger fails

### ISSUE THREAD

**Issue by mmussett** [project-flogo/messaging-contrib#16]
Created a simple flow with return activity. 

Deployed to Pulsar using:
pulsar-admin functions create \
--go /home/mmussett/Downloads/pulsar-functions_linux_amd64  \
-i persistent://public/default/to-flogo \
-o persistent://public/default/from-flogo \
--classname empty

Pulsar reporting errors in console:

15:45:25.371 [function-timer-thread-100-1] INFO  org.apache.pulsar.functions.runtime.process.ProcessRuntime - Started process successfully
2021/01/04 15:45:25.375 log.go:46: [info] The default config file path is: conf/conf.yaml
2021/01/04 15:45:25.381 log.go:76: [error] unmarshal config content error:invalid character '\'' looking for beginning of value
panic: config file is nil.

goroutine 1 [running]:
github.com/apache/pulsar/pulsar-function-go/pf.newInstanceConf(0xaf9d80)
	/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20200819065839-6cae4afac3c3/pf/instanceConf.go:49 +0x682
github.com/apache/pulsar/pulsar-function-go/pf.NewFuncContext(...)
	/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20200819065839-6cae4afac3c3/pf/context.go:35
github.com/apache/pulsar/pulsar-function-go/pf.newGoInstance(0xae6dc0)
	/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20200819065839-6cae4afac3c3/pf/instance.go:65 +0x38
github.com/apache/pulsar/pulsar-function-go/pf.Start(0xae6dc0, 0xc07890)
	/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20200819065839-6cae4afac3c3/pf/function.go:170 +0x52
main.main()
	/flogo-web/local/engines/app-build/src/shim.go:10 +0x39
15:45:55.254 [pulsar-web-68-4] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [04/Jan/2021:15:45:55 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false HTTP/1.1" 200 1396 "-" "Pulsar-Java-v2.7.0" 2
15:45:55.368 [function-timer-thread-100-1] ERROR org.apache.pulsar.functions.runtime.process.ProcessRuntime - Extracted Process death exception
java.lang.RuntimeException: 
	at org.apache.pulsar.functions.runtime.process.ProcessRuntime.tryExtractingDeathException(ProcessRuntime.java:388) ~[org.apache.pulsar-pulsar-functions-runtime-2.7.0.jar:2.7.0]
	at org.apache.pulsar.functions.runtime.process.ProcessRuntime.isAlive(ProcessRuntime.java:375) ~[org.apache.pulsar-pulsar-functions-runtime-2.7.0.jar:2.7.0]
	at org.apache.pulsar.functions.runtime.RuntimeSpawner.lambda$start$0(RuntimeSpawner.java:86) ~[org.apache.pulsar-pulsar-functions-runtime-2.7.0.jar:2.7.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
15:45:55.368 [function-timer-thread-100-1] ERROR org.apache.pulsar.functions.runtime.RuntimeSpawner - public/default/empty-java.lang.RuntimeException:  Function Container is dead with exception.. restarting

No response from function when sending message to Pulsar...

pulsar-client consume -s flogo-sub persistent://public/default/from-flogo
pulsar-client produce -m "Flogo" persistent://public/default/to-flogo

**Comment by mmussett** [comment]
Running Pulsar 2.7.0. Repeatable on both Mac and Linux OS

**Comment by mmussett** [comment]
Flogo app.json and build image for Linux attached...

[pulsar.zip](https://github.com/project-flogo/messaging-contrib/files/5765562/pulsar.zip)
